### PR TITLE
Ignore .idea files from RubyMine

### PR DESCRIPTION
**Pull request by tomarra**

### CODE REVIEW

**Comment by adamkiczula** [comment]
idea files are the project files for RubyMine

**Comment by yuriy1337** [comment]
Ahhh its an ide. How is that one? Also has anyone tried Aptana RadRails?

**Comment by adamkiczula** [comment]
RubyMine is pretty awesome, has all the things you would want in an IDE, including GIT integration :D

**Comment by yuriy1337** [comment]
Neat, I will have to try it.

**Pull request merged**
