### PR TITLE
Start of themeing

### PR DESCRIPTION
**Pull request by tomarra**
This is a big change but is needed. Please pull this in ASAP.

### CODE REVIEW

**Comment by adamkiczula** [comment]
did you generate some new files? there shouldn't be a users index/show/edit view.

**Comment by tomarra** [comment]
There will be some clean up needed as the generator did a lot of that. I wanted to get this checked in so there wasn't a ton of merges while you guys were working.

**Comment by yuriy1337** [comment]
Yea there is A LOT of stuff there. Should this be reopened?

**Comment by tomarra** [comment]
No. Everyone please pull down these changes and regression test. I tired to minimize the issues but I have a feeling the theme generator may have stepped on some of our custom stuff.

**Pull request merged**
