### PR TITLE
Fix error on all selections view

### PR DESCRIPTION
**Pull request by tomarra**
Removing category from selections index view. I don't think that it's needed on that view. Also it was giving an error.

### CODE REVIEW

**Comment by adamkiczula** [comment]
It would only throw an error if the category were invalid. Are you sure you had a valid id for the category_id in place?

**Comment by yuriy1337** [comment]
Yea the db got all messed up before as the forms weren't working. Its not necessary but kind of nice to have the category name also.

**Comment by adamkiczula** [comment]
We should probably dump the DB and start over now, I also just added a bunch of stuff for validations.

**Comment by yuriy1337** [comment]
Agreed. I've had to dump the db several times now in my dev environment.

**Pull request merged**
